"""Adding role field in User relation

Revision ID: 51a75403f3b4
Revises: 8ef8251fe78d
Create Date: 2025-07-03 13:59:25.892572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a75403f3b4'
down_revision: Union[str, None] = '8ef8251fe78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE user_role AS ENUM ('admin', 'author', 'user')")

    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'AUTHOR', 'USER', name='user_role', create_constraint=True), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
 